### login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 1|xZeNy9ysh1Mwg7qVYOwdJ1ywxmbENWKLxzJdDruw8fe05a8e

### salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 1|xZeNy9ysh1Mwg7qVYOwdJ1ywxmbENWKLxzJdDruw8fe05a8e
