### Listado
GET http://127.0.0.1:8000/api/user
Accept: application/json
Authorization: Bearer 9|ifuHdPV0THCO30KaXPd2Jv50ytOu9Ju0qWbIruwd3c9970a0

### Guardar
POST http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json

{
    "name": "juan",
    "email": "juan@mail.com",
    "password": "juan54321"
}

### Mostrar
GET http://127.0.0.1:8000/api/user/3
Accept: application/json

### Modificar
PUT http://127.0.0.1:8000/api/user/3
Accept: application/json
Content-Type: application/json

{
    "name": "sergio rodriguez",
    "email": "sergio@mail.com",
    "password": "sergio123"
}

### Eliminar

DELETE http://127.0.0.1:8000/api/user/1
